ci: update

diff --git a/.github/workflows/generatechangelog.yml b/.github/workflows/generatechangelog.yml
--- a/.github/workflows/generatechangelog.yml
+++ b/.github/workflows/generatechangelog.yml
@@ -40,9 +40,9 @@ jobs:
               echo "-------- step 2.5 --------------" $history_feat
               echo -e '\nFx-core feat commits:\n' "$history_feat" '\n\n'> "$temp_file"
               echo "======== step 3 =============="
-              history_fix=$(git log --pretty=format:"%s %h" $head...HEAD | grep "^fix")
+              history_fix=$(git log --pretty=format:"%s %h" $head...HEAD | grep "^fix") || echo "step 3 - 3.5 failed"
               echo -e "-------- step 3.5 --------------" $history_fix
-              echo -e '\nFx-core fix commits:\n' "$history_fix" '\n\n'>> "$temp_file"
+              echo -e '\nFx-core fix commits:\n' "$history_fix" '\n\n'>> "$temp_file" || echo "no such content"
               echo "======== step 4 =============="
               cat PRERELEASE.md >> "$temp_file"
               mv "$temp_file" PRERELEASE.md
